UPDATE users SET age = '21' WHERE user_id = 11
-- SE USA PARA ACTUALIZAR LA BASE DE DATO, SIEMPRE ACOMPAÑADO DE WHERE SINO ES PELIGROSO

UPDATE users SET age = 20, init_date = '2024-06-18' WHERE user_id = 11
-- ACTUALIZAMOS DOS CAMPOS AGE Y INIT_DATE EL AGE SIN ' ' 
