CREATE VIEW v_adult_users AS
SELECT name, age
FROM users
WHERE age >=18;

SELECT * FROM v_adult_users

-- CREAMOS UNA VISTA LLAMADA v_adult_users DONDE LE PEDIMOS MOSTRAR LOS USUARIOS MAYORES DE 18 AÑOS
-- LAS VISTAS SE UTILIZAN CUANDO SE CONSULTAN VARIAS VECES EL MISMO DATO

DROP VIEW v_adult_users
-- ELIMINAMOS LA VISTA
