-- PROCEDIMIENTOS ALMACENADOS (SIMILAR A UNA COOKIE)
DELIMITER //
CREATE PROCEDURE p_all_users()
BEGIN
SELECT * FROM users;
END
// 

CALL p_all_users();
CALL p_all_users
-- ASI LLAMAMOS AL PROCEDIMIENTO ALMACENADO

DELIMITER //
CREATE PROCEDURE p_age_users(IN age_param INT)
BEGIN
SELECT * FROM users WHERE age = age_param;
END
// 

CALL p_age_users(30)
-- CONSULTAMOS EL PROCEDIMIENTO Y PEDIMOS VER LOS USUARIOS CON 30 AÑOS

DROP PROCEDURE p_age_user
-- BORRA EL PROCEDIMIENTO
