SELECT * FROM users; /* MUESTRA TODOS LOS DATOS DE LA TABLA */

SELECT name FROM users;  /* MUESTRA LOS NOMBRES SOLAMENTE DE LA TABLA */

SELECT users_id, name FROM users;  /*MUESTRA LOS ID DE LOS USUARIOS Y LOS NOMBRES */

