SELECT * FROM users WHERE age = 15   /* MUESTRA SOLAMENTE LOS USUARIOS COMPLETOS DE AGE = 15 */

SELECT NAME FROM users WHERE age = 15 /* MUESTRA SOLAMENTE LOS NOMBRE DE LOS USUARIOS DE EDAD 15 */

SELECT distinct age FROM users WHERE age = 15 /* MUSTRA SOLAMENTE 1 SOLO 15 */

