SELECT max(age) FROM users group by age 
-- MUESTRA LAS EDADES AGRUPADAS POR EDADES DESDE EL MAXIMA

SELECT COUNT(AGE), AGE FROM users group by AGE 
-- CUENTA LAS EDADES QUE HAY DE CADA CAMPO Y LAS AGRUPA POR EDADES

SELECT COUNT(AGE), AGE FROM users group by AGE ORDER BY AGE ASC
-- CUENTA LAS AGE Y LAS AGRUPA POR EDADES Y LAS ORDENA POR AGE ASCENDENTES

SELECT COUNT(AGE), AGE FROM users WHERE age > 15 group by AGE ORDER BY AGE ASC
-- CUENTA LAS AGE Y LAS AGRUPA POR EDADES ORDENADAS ASCENDENTE MAYORES A 15 AGE

