ALTER TABLE persons8 
ADD surname varchar(100)

-- ALTERAMOS LA TABLA AGREGANDOLE SURNAME DE 100 CARACTERES

ALTER TABLE persons8 
RENAME COLUMN surname TO Descripcion;

-- ALTERAMOS PARA RENOMBRAR UN CAMPO DE LA COLUMNA

ALTER TABLE persons8 
MODIFY COLUMN Descripcion varchar(250);

-- MODIFICAMOS LOS ATRIBUTOS DE LA TABLA 

ALTER TABLE persons8 
DROP COLUMN Descripcion;

-- ELIMINAMOS LA COLUMNA DESCRIPCION DE LA TABLA